# The build.yml file defines 1 or more top level targets.

# Each target must define a list of modules, a platform, and a cpu type.


linux-x64:
  modules:
    runtime: linux-runtime
    foolib: foolib1_0
    barlib: barlib2_1
  platform: linux
  cpu: x64


linux-x86:
  modules:
    foolib: foolib1_0
    barlib: barlib2_0
    main: main
  platform: linux
  cpu: x86
  executables:
    main: linux-x86/main

windows:
  modules:
    runtime: windows-runtime
    foolib: foolib1_0
    barlib: barlib2_0
    main: main_experimental_windows
  platform:
    - windows
  cpu:
    - x64
    - x86




