// Copyright 2026 Ryan P. Nicholl, rnicholl@protonmail.com

#ifndef QUXLANG_CORTADO_BACKEND_TYPES_HEADER_GUARD
#define QUXLANG_CORTADO_BACKEND_TYPES_HEADER_GUARD

#include <quxlang/data/dependencies.hpp>
#include <quxlang/data/enum_flagset_info.hpp>
#include <quxlang/data/fusion_info.hpp>
#include <quxlang/data/struct_field_declaration.hpp>
#include <quxlang/data/target_configuration.hpp>
#include <quxlang/vmir2/source_index.hpp>
#include <quxlang/vmir2/vmir2.hpp>

#include <cstdint>
#include <map>
#include <optional>
#include <rpnx/cow.hpp>
#include <set>
#include <string>
#include <vector>

/** Identifies the JVM bytecode operation used by a resolved external callable. */
RPNX_ENUM(quxlang::cortado_backend, jvm_call_kind, std::uint8_t, static_method, virtual_method, interface_method, constructor, get_static, put_static, get_field, put_field);

namespace quxlang::cortado_backend
{
    /** Describes one reached JVM nominal external type. */
    struct jvm_external_type_info
    {
        /// Java platform module that supplies the class.
        std::string source_name;
        /// Slash-separated JVM internal class name.
        std::string internal_name;

        RPNX_MEMBER_METADATA(jvm_external_type_info, source_name, internal_name);
    };

    /** Describes one source-level argument of a resolved JVM external callable. */
    struct jvm_external_parameter
    {
        /// Named Quxlang API argument, or no value for a positional argument.
        std::optional< std::string > api_name;
        /// Canonical Quxlang argument type.
        type_symbol type;

        RPNX_MEMBER_METADATA(jvm_external_parameter, api_name, type);
    };

    /** Contains a fully validated JVM method or field binding. */
    struct resolved_jvm_external_callable
    {
        /// Slash-separated JVM owner class.
        std::string owner_internal_name;
        /// JVM method or field name.
        std::string member_name;
        /// Bytecode operation selected by CALLCONV.
        jvm_call_kind call_kind = jvm_call_kind::static_method;
        /// Exact JVM method or field descriptor.
        std::string descriptor;
        /// Ordered source-level parameters, including THIS and VALUE where declared.
        std::vector< jvm_external_parameter > parameters;
        /// Canonical Quxlang return type when the binding returns a value.
        std::optional< type_symbol > return_type;

        RPNX_MEMBER_METADATA(resolved_jvm_external_callable, owner_internal_name, member_name, call_kind, descriptor, parameters, return_type);
    };

    /** Identifies one unit test and the VMIR routine generated for it. */
    struct unit_test_entry
    {
        /// Stable diagnostic name of the unit test.
        std::string name;
        /// Symbol of the VMIR routine invoked by the generated test runner.
        type_symbol procedure_symbol;

        RPNX_MEMBER_METADATA(unit_test_entry, name, procedure_symbol);
    };

    /** Contains the layout-independent closure required to generate one Cortado JAR. */
    struct cortado_compilable_unit
    {
        /// Configured output name used for diagnostics and deterministic identity.
        std::string output_name;
        /// Output category generated by Cortado.
        output_kind kind = output_kind::executable;
        /// Effective backend settings for this output.
        backend_cortado_options options;
        /// Entry routine for an executable output.
        std::optional< type_symbol > entry_procedure;
        /// Unit-test routines invoked by a unit-test-suite output.
        std::vector< unit_test_entry > unit_tests;
        /// Complete runtime-reachable VMIR routine closure.
        std::map< type_symbol, vmir2::functanoid_routine3 > routines;
        /// Reached JVM nominal external types keyed by their Quxlang symbols.
        std::map< type_symbol, jvm_external_type_info > external_types;
        /// Reached and validated JVM method and field bindings.
        std::map< type_symbol, resolved_jvm_external_callable > external_callables;
        /// Quxlang runtime procedures selected to implement reached runtime facilities.
        std::map< vmir_runtime_dependency, type_symbol > resolved_runtime_procedures;
        /// Source-location index retained for diagnostics and optional debug emission.
        std::optional< rpnx::cow< vmir2::source_index > > source_index;
        /// Runtime facilities reached by the VMIR closure.
        std::set< vmir_runtime_dependency > runtime_requirements;
        /// Declared types of reached globals and static snapshots.
        std::map< type_symbol, type_symbol > global_types;
        /// Compile-time values of reached globals and static snapshots.
        std::map< type_symbol, antestatal_value > global_values;
        /// Dense canonical type ordinals used throughout this generated JAR.
        std::map< type_symbol, std::uint64_t > type_index_ordinals;
        /// Semantic field declarations of reached struct types.
        std::map< type_symbol, std::vector< struct_field > > struct_definitions;
        /// Declared alternative memberships of reached TYPED_STORAGE types.
        std::set< type_symbol > storage_definitions;
        /// Semantic definitions of reached enum types.
        std::map< type_symbol, enum_info > enum_definitions;
        /// Semantic definitions of reached flagset types.
        std::map< type_symbol, flagset_info > flagset_definitions;
        /// Semantic definitions of reached union types.
        std::map< type_symbol, union_info > union_definitions;
        /// Semantic definitions of reached variant types.
        std::map< type_symbol, variant_info > variant_definitions;

        RPNX_MEMBER_METADATA(cortado_compilable_unit, output_name, kind, options, entry_procedure, unit_tests, routines, external_types, external_callables, resolved_runtime_procedures, source_index, runtime_requirements, global_types, global_values, type_index_ordinals, struct_definitions, storage_definitions, enum_definitions, flagset_definitions, union_definitions, variant_definitions);
    };
} // namespace quxlang::cortado_backend

#endif // QUXLANG_CORTADO_BACKEND_TYPES_HEADER_GUARD
